<math mode="display" xmlns="http://www.w3.org/1998/Math/MathML">
    <semantics>
        <mrow>
            <mi>r</mi>
            <mo>=</mo>
            <mfrac>
                <mrow class="mb-2">
                    <mi>n</mi>
                    <mo>&#8290;</mo>
                    <mo>(</mo>
                    <mo>&#8290;</mo>
                    <mo>&sum;</mo>
                    <mi>x</mi>
                    <mi>y</mi>
                    <mo>)</mo>
                    <mo>&#8290;</mo>
                    <mo>-</mo>
                    <mo>(</mo>
                    <mo>&#8290;</mo>
                    <mo>&sum;</mo>
                    <mi>x</mi>
                    <mo>)</mo>
                    <mo>&#8290;</mo>
                    <mo>(</mo>
                    <mo>&#8290;</mo>
                    <mo>&sum;</mo>
                    <mi>y</mi>
                    <mo>)</mo>
                </mrow>
                <mrow>
                    <msqrt class="mt-2">
                        <mrow class="mt-2 mx-2">
                            <mo>(</mo>
                            <mi>n</mi>
                            <mo>&#8290;</mo>
                            <mo>&sum;</mo>
                            <msup>
                                <mi>x</mi>
                                <mn>2</mn>
                            </msup>
                            <mo>-</mo>
                            <msup>
                                <mo>(</mo>
                                <mo>&#8290;</mo>
                                <mo>&sum;</mo>
                                <mi>x</mi>
                                <mo>)</mo>
                                <mn>2</mn>
                            </msup>
                            <mo>)</mo>
                            <mo>(</mo>
                            <mi>n</mi>
                            <mo>&#8290;</mo>
                            <mo>&sum;</mo>
                            <msup>
                                <mi>y</mi>
                                <mn>2</mn>
                            </msup>
                            <mo>-</mo>
                            <msup>
                                <mo>(</mo>
                                <mo>&#8290;</mo>
                                <mo>&sum;</mo>
                                <mi>y</mi>
                                <mo>)</mo>
                                <mn>2</mn>
                            </msup>
                            <mo>)</mo>
                        </mrow>
                    </msqrt>
                </mrow>
            </mfrac>
        </mrow>
    </semantics>
</math>
